### PR TITLE
Simple Classifiers - SJ

### PR DESCRIPTION
**Pull request by sameerjvn**

### CODE REVIEW

**Comment by sameerjvn** [comment]
Trained and Tested Logistic Regression Classifier Model
"Condition" feature is included in the input, missing values are imputed using most frequent value.
Output - breed category
Confusion Matrix:
[[1523  215   39]
 [ 139 1537    0]
 [ 166    0  148]]
f1_score:  0.8467998969028573

**Comment by sameerjvn** [comment]
Trained and Tested k-NearestNeighbor Classifier Model
Model saved as knn_clf.pkl
"Condition" feature is included in the input, missing values are imputed using most frequent value.
Output - breed category
Confusion Matrix: 
[[1540  170   67]
 [ 202 1473    1]
 [ 124    0  190]]
f1_score on:  0.8491171321183673

**Comment by kevingeo11** [comment]
I can only find the logistic regression notebook
That's weird.... :/

**Comment by sameerjvn** [comment]
That's because I made a fork of the repo _after_ I created the branch and the first couple of commits. I'll have to merge this PR to the simple_clfs_sj branch for you to be able to see the changes.

**Pull request merged**
